eclipse-ee4j/krazo

.github/issue_template.md, .github/pull_request_template.md
There are still issue / pull request templates which tell people to NOT use the repository. I forgot to exclude them from the initial contribution.
Let's see if the Travis integration works....
=> Removed old GitHub templates

pom.xml
I'm currently working on getting the Krazo snapshots to the OSSRH repository. The PR contains two important fixes for our pom.
- Currently Krazo doesn't build correctly on our [Jenkins instance](https://jenkins.eclipse.org/krazo/), because it depends on a snapshot version of the TCK. On Travis the OSSRH snapshot repository is enabled automatically, but this is not the case on Jenkins. Therefore, I added a special profile which can be used to enable the snapshot repository for the pom.
- The other commit tweaks the GPG arguments used when signing the artifacts. Newer versions of GPG require this option to be set, so we can sign the artifacts when running snapshot deployments and/or releases from Jenkins. This is also documented in the [EE4J …
=> Some pom.xml improvements

core/pom.xml, core/src/test/java/org/eclipse/krazo/util/AnnotationUtilsTest.java, cxf/pom.xml, jersey/pom.xml, pom.xml, resteasy/pom.xml
As we need to file some CQs for our dependencies, I did some cleanup to reduce the number of dependencies for the krazo-core module:
* I replaced the umbrella `javaee-web-api` dependency with individual spec API JARs. A few of them were already released under the new `jakarta.*` groupId, so we don't need to file additional CQs for them. This will also allow us to update individual spec dependencies more easily.
* There were some test scoped dependencies which were actually unused. I removed them from the pom.
* We had a few Apache Deltaspike dependencies just for a single test which required to bootstrap a full CDI container. I updated the test to manually bootstrap Weld using the Weld API which is actually very easy. So I was able to get rid of the Deltaspike dependency.
I'll create CQs …
=> Major cleanup of Krazo dependencies

core/src/main/java/org/eclipse/krazo/binding/validate/ValidationInterceptor.java
The log message here is incorrect and is causing an exception if the log level is enabled.
=> Fixed broken trace log message

.travis/docker-wildfly.sh, .travis/tests.sh, .travis/wlp-server-template.xml, tck/pom.xml
This PR updates the container versions we run the TCK tests against:
* Glassfish 5.1.0-RC1 to Eclipse Glassfish 5.1.0.Final
* Wildfly 14.0.1.Final to 15.0.1.Final
* TomEE 7.1.0 to 8.0.0-M2
* Liberty 18.0.0.3 to 19.0.0.1
I checked the build results and everything looks fine (which means that the builds are still failing due to the compatibility issues we already know about).
=> Updated all integration test containers to latest version

core/src/main/java/org/eclipse/krazo/binding/convert/MvcConverterProvider.java, core/src/main/java/org/eclipse/krazo/security/CsrfExceptionMapper.java
Some of our JAX-RS providers were missing `@Priority` annotations to enforce a specific ordering. I think that I omitted them back then because I wasn't seeing consistent behavior with Jersey 2.26 anyway. But as we are not targeting more servers, we should specify them correctly. Maybe this will work with Jersey 2.28 now.
=> Set more provider priorities for correct ordering

core/src/main/java/org/eclipse/krazo/KrazoConfig.java
This PR contains the required changes to support customizable CSRF HTTP header names as introduced in the spec via mvc-spec/mvc-spec#209. 
Krazo currently still depends on the `1.0-pfd` release of the spec and I would like to keep this, so we can release as soon as possible without also having to release the spec. Therefore, I hardcoded the constants which were introduced in the spec.
=> Allow to change name of CSRF HTTP header

core/src/main/java/org/eclipse/krazo/binding/convert/impl/DoubleConverter.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/FloatConverter.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/IntegerConverter.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/LongConverter.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/NumberConverter.java
I'm currently working on the TCK tests for the data binding chapter and ran into an NPE that is caused by a bug in Krazo. Basically the code wasn't handling empty strings correctly if they were bound to numeric types. For empty strings the correctly result should be either `null` (for wrapper types) or `0` for primitive types.
I think the diff is self-explanatory. `parseNumber` returned `null` for empty strings, but the calling code was just calling `.doubleValue()` (and other type dependent methods) on it without checking for `null`. With this fix applied I'm getting more green TCK tests! :+1:
=> Fixed NPE when binding empty strings to numeric types

core/src/main/java/org/eclipse/krazo/binding/convert/ConverterRegistry.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/BigDecimalConverter.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/BigIntegerConverter.java
I just noticed that we forgot to add MVC binding support for the data types `BigDecimal` and `BigInteger` as required by the spec.
=> Added binding support for BigDecimal/BigInteger

core/src/main/java/org/eclipse/krazo/binding/convert/ConverterRegistry.java, core/src/main/java/org/eclipse/krazo/binding/convert/impl/ShortConverter.java, core/src/test/java/org/eclipse/krazo/binding/convert/ConverterRegistryTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/BigDecimalConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/BigIntegerConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/BooleanConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/ConversionTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/DoubleConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/FloatConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/IntegerConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/LongConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/ShortConverterTest.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/SupportsTest.java
I was doing some low-energy work and started testing the converter package. There are some edge-cases that we don't handle correctly:
* Float and Double usually return NaN - but not always
* There were uncaugt NumberFormatExceptions with BigDecimal and BigInteger
There are still some flaky tests, which I left commented out - the parse behavior slightly changed from Java 8 to 11. It's not that bad, but a little supprising ("NaN" is a valid Number and won't trigger binding errors).
It's a little strange that nearly all converters handle numbers, but we don't have a converter that supports the abstract `Number`-Type as a result. Should we pick one that handles this (Double?)
We also forgot about `Short` should we add a converter for it?
=> Test the binding package and fixed some minor issues

core/src/main/java/org/eclipse/krazo/engine/Viewable.java
When a ViewEngine is not found for a view, the Viewable's Object#toString is called and the message in the stacktrace is not really helpful. This way it should simply print the Viewable#view to identify what causes the exception.
=> Print view in Viewable toString for easier debugging

.travis.yml, .travis/tests.sh
I adjusted our test script to replace one of the Jersey modules shipping with Eclipse Glassfish 5.1.0 with a patched version. Let see if this fixes some of the errors we get when running the TCK against Eclipse Glassfish 5.1.0.
Travis, please test! :-)
=> Patch Jersey version in Glassfish 5.1.0 for TCK

core/src/main/java/org/eclipse/krazo/binding/convert/impl/BooleanConverter.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/BooleanConverterTest.java
The spec states:
> Empty strings are converted to `false` in case of the primitive boolean type and to `null` for the wrapper type.
Krazo doesn't handle this case correctly which causes a broken TCK test.
=> Fixed BooleanConverter to handle empty strings correctly

core/src/main/java/org/eclipse/krazo/servlet/KrazoServletContextListener.java
Make exception more clear when controllers are not managed CDI neans, so users understand the issue and how to fix it.
closes #63 
Signed-off-by: Gregor Tudan <gregor@tudan.de>
=> Clarify exception message when Controllers are not CDI managed

.travis.yml, .travis/tests.sh
This PR creates a new TCK profile for running against a patched version of Wildfly 16. Unfortunately the handling of validation errors is currently broken in Wildfly 16 because of [WELD-2568](https://issues.jboss.org/browse/WELD-2568). This issue has been fixed for the current Weld snapshots (see weld/core#1907). I backported the fix and the new profile basically just replaces the corresponding Weld JAR file.
I hope that the `*-patched` profiles allow us to verify that Krazo works flawless on the upcoming Wildfly release. :-)
=> Added new TCK profile for patched Wildfly 16

.travis.yml, .travis/tests.sh
This PR contains the following changes:
* I refactored the `tests.sh` script to make it easier to maintain
* I backported eclipse-ee4j/jersey#4103 and patched the corresponding Jersey JAR file
With this PR Krazo now passes the TCK for a patched version of Eclipse Glassfish 5.1! :beers:
=> Apply another Jersey fix in the (patched) Glassfish TCK profile

.travis.yml, .travis/tests.sh
I added another quickfix to the `tck-wildfly16-patched`. And: Good news! The TCK passes now! :tada: 
The fix is a simple workaround for [RESTEASY-2222](https://issues.jboss.org/browse/RESTEASY-2222). Let's hope they are willing to accept a corresponding patch.
@gtudan IIRC we talked about some Wildfly specific CSRF failure at JavaLand? Do you remember any details about this failure? For some reason the TCK is green now!
=> Added fix for RESTEASY-2222 to patched wildfly profile

.travis.yml, .travis/tests.sh
The PR adds a new TCK profile for the upcoming Wildfly 17 release. Currently, it looks like Krazo will pass the TCK on Wildfly 17 without any additional patches. As Wildfly 17 isn't released yet, this profile uses the latest nightly builds of Wildfly.
=> Added TCK profile for Wildfly 17

.travis/tests.sh
There is now an official Wildfly 17.0.0.Beta1. So we should run the TCK against this version.
=> Run TCK against Wildfly 17.0.0.Final

.travis/docker-wildfly.sh
This updates the testsuite to the latest Wildfly version. 
The good news: no regressions \o/. Sad news: still some issues with module loading with jruby/jython.
=> Run the testsuite against the lastest WF-Release (17)

.travis.yml, .travis/tests.sh
Wildfly 17 has been released and is passing the TCK. So I guess it makes sense to remove the old Wildfly 16 CI profiles .
=> Removed Wildfly 16 TCK profiles

.travis.yml, core/src/main/java/org/eclipse/krazo/forms/HiddenMethodFilter.java
I just noticed that our [nighly build](https://jenkins.eclipse.org/krazo/job/nightly/) running on Eclipse Jenkins was broken for quite some time. The issue was that running the build with the release profile (which creates javadocs, source code attachments, etc.) failed because one class contained invalid HTML in the API docs.
This PR fixes the HTML issue and updates the Travis build to activate the release profile for the build (excluding the GPG signature).
=> Run Travis build with javadoc generation enabled

tck/pom.xml
Now as we have an [approved CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20315) for TomEE 8.0.0-M3, we should also run the TCK against this version.
=> Updated TCK module to run TCK against TomEE 8.0.0-M3

ext/jetbrick/pom.xml
Apps using the jetbricks extension fail to deploy if the container runs on Java 9 (or newer). This affects the Wildfly- (#70) as well as the new TomEE-Testsuite (#76).
The issue has been fixed upstream, so all we need to do is update.
=> Updated Jetbricks to support containers running with Java 9+

.travis.yml, .travis/docker-tomee.sh, testsuite/pom.xml, testsuite/src/test/resources/arquillian.xml
Still working on improving the testsuite and making sure our extensions work with different providers.
This runs the integration-tests from the testuite against TomEE 7, so we get some coverage for CXF.
There are failures, but only two. I'm a pleasantly surprised :-)
* The Pebble Ext doesn't work - I will try to look into it.
* The hidden forms IT fails when using the patch-method. I'll file an issue for it. @erdlet could you please take a look?
=> Run testsuite against TomEE

.travis.yml, dependency-check-suppressions.xml, examples/validation-i18n/pom.xml, ext/asciidoc/pom.xml, ext/handlebars/pom.xml, ext/pebble/pom.xml, ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleConfigurationProducer.java, ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleEngineProducer.java, ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleProperty.java, ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleViewEngine.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/CustomEscapingStrategy.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/CustomExecutorService.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/CustomExtensionOne.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/CustomExtensionTwo.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/PebbleConfigurationProducerTest.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/PebbleEngineProducerTest.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/PebblePropertyTest.java, ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/PebbleViewEngineTest.java, pom.xml
Some of the dependencies used in the ext packages got a little dated and have known vulnerabilities.
This adds the [OWASP Dependency Check](https://www.owasp.org/index.php/OWASP_Dependency_Check) as stage to Travis to help us monitor the issues. The plugin also generates a nice HTML report under target/ in the project base dir that helps to understand what's wrong and where the broken dependencies came from.
I started fixing some of the issues by updating the dependencies. The testsuite looks good (yay!) but I'm pretty sure we need to go through some paperwork to get the new versions approved by eclipse.
For comparison: here's the test before those fixes: https://travis-ci.org/gtudan/krazo/jobs/546367007
There are still some issues left in these extensions, so I filed upstream issues for …
=> add OWASP Dependency-Check to scan for vulnable components

.travis.yml
Travis builds have become a little slow. This caches dependencies so we don't have to download them every time
=> cache maven dependencies in travis build

.travis.yml
Glassfish 5.1 is known to not work correctly with Krazo because of known issues in Jersey 2.28 which have been fixed in 2.29. So I don't think it makes sense to keep the `tck-glassfish51-vanilla` anymore. Hopefully there will be a new Glassfish release soon with an updated Jersey version.
=> Removed tck-glassfish51-vanilla profile

.travis.yml
Looks like the build currently breaks because Travis doesn't support OracleJDK8 anymore.
Let's get this one in quickly.
=> Use openjdk8 instead of oraclejdk8 for Travis

.travis.yml, pom.xml
This detects Java 9 and above and sets the `maven.compiler.release` property.
This makes the Java compiler generate Java 8 byte code, so we keep backwards compatibility with older Java versions.
Closes #97
=> Allow building with Java 9 and above

.travis.yml
The testsuites for wildfly and tomee are finally green. We can remove the travis whitelist before they break again 😛
=> Un-whitelist green testsuites

.travis.yml
I just noticed that we don't execute the unit tests during the travis build. All stages have `-DskipTests`.
Here's a failing test. The build is still green.
https://github.com/gtudan/krazo/commit/3ac2c34899efe47c1cdc63c6763a6435713b380b
Let's add a stage that runs them.
=> run the unit tests in travis

CONTRIBUTING.md
This pull request adds the link to the EE4J code format rules to the CONTRIBUTING.md file
=> Added code format reference to CONTRIBUTING.md (fixes #105)

core/src/main/java/org/eclipse/krazo/cdi/types/AnnotatedTypeProcessor.java, core/src/main/java/org/eclipse/krazo/core/ViewResponseFilter.java, core/src/main/java/org/eclipse/krazo/lifecycle/RequestLifecycle.java, core/src/main/java/org/eclipse/krazo/util/AnnotationUtils.java, core/src/main/java/org/eclipse/krazo/util/ControllerUtils.java, examples/exceptions/pom.xml, examples/exceptions/src/main/java/org/eclipse/krazo/test/exceptions/HelloController.java, examples/exceptions/src/test/java/org/eclipse/krazo/test/exceptions/ExceptionsIT.java, examples/view-annotation/src/main/java/org/eclipse/krazo/test/view/HelloController.java, examples/view-annotation/src/test/java/org/eclipse/krazo/test/view/ViewAnnotationIT.java, testsuite/pom.xml, testsuite/src/main/java/org/eclipse/krazo/test/mapper/FailingController.java, testsuite/src/main/java/org/eclipse/krazo/test/mapper/MvcViewException.java, testsuite/src/main/java/org/eclipse/krazo/test/mapper/MvcViewExceptionMapper.java, testsuite/src/main/java/org/eclipse/krazo/test/mapper/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/mapper/PlainTextException.java, testsuite/src/main/java/org/eclipse/krazo/test/mapper/PlainTextExceptionMapper.java, testsuite/src/test/java/org/eclipse/krazo/test/mapper/ExceptionMapperIT.java
This pull requests contains the refactoring described in #104. Actually the change is quite simple. The request-scoped`RequestLifecycle` class just tracks if the controller was invoked successfully and the `VewiResponseFilter` only runs if this is the case. 
The PR contains integration tests which checks 3 different scenarios:
* If the controller execution is successful, the request is processed just like before.
* If the controller throws an exception and an exception mapper creates a plain text response, this must work exactly like in a plain JAX-RS application (and NOT trigger a view engine lookup)
* If the controller throws an exception and an exception mapper wants to render an MVC view, it can simple use a `Viewable` as the entity.
I guess this should cover all the relevant cases. …
=> Run ViewResponseFilter only if controller was executed successfully

ext/velocity/pom.xml, ext/velocity/src/main/java/org/eclipse/krazo/ext/velocity/DefaultVelocityEngineProducer.java, ext/velocity/src/main/java/org/eclipse/krazo/ext/velocity/ServletContextResourceLoader.java, pom.xml
This PR removes our dependency on `velocity-tools-view`. I added a custom resource loader which replaces the one we used from the old dependency. Our new custom implementation doesn't support any caching at the moment, but I don't think that this is a real problem. Especially because most of the other 3rd party view engines also don't support a caching mechanism.
I also updated Velocity Engine from 2.0 to 2.1. There is a [CQ](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21009) which was already approved
I was also able to remove the `<dependencyManagement>` entry we needed due to the outdated `commons-beanutils` dependency in Velocity Tools.
=> Add custom resource loader for Velocity view engine

core/pom.xml, examples/validation-i18n/pom.xml, jersey/pom.xml, resteasy/pom.xml
see: #111
As Jakarta EE 8 is released since a few weeks and all necessary APIs are transferred to Jakarta, it makes sense to use them everywhere.
=> Replace javax dependencies with jakarta dependencies.

examples/pom.xml, ext/pom.xml, tck/pom.xml, testsuite/pom.xml
We currently don't have a CQ for the Java EE 7 dependency. And as we need Java/Jakarta EE 8 anyway, let's update this now.
=> Updated Java EE API with Jakarta EE version

documentation/pom.xml, documentation/src/main/asciidoc/_intro.adoc, documentation/src/main/asciidoc/index.adoc, pom.xml
This PR creates a new `documentation` module for the Krazo project documentation. Please note that this PR only provides a first minimal version of this module. We still need to discuss how to organize the chapters, push the latest version to the website, etc.
=> First version of documentation module

testsuite/pom.xml, testsuite/src/test/java/org/eclipse/krazo/test/CsrfIT.java, testsuite/src/test/java/org/eclipse/krazo/test/MvcIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/AsciiDocIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/FreemarkerIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/HandlebarsIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/JadeIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/JetbrickIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/Jsr223IT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/JtwigIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/MustacheIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/PebbleIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/StringTemplateIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/ThymeleafIT.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/VelocityIT.java
see: #134
Because arquillian-drone relies on outdated versions of e.g. htmlunit, the tests use now
plain htmlunit and drone is removed
=> Replace arquillian-drone with plain htmlunit

.travis/tests.sh, pom.xml, tck/pom.xml
The 1.0.0 releases of the API and TCK are now available in Maven Central. So let's update our deps.
PS: I'll create the CQs later today.
PPS: I'll cherry-pick this commit to the Krazo 1.0.0 release branch after the merge.
=> Updated API and TCK to 1.0.0

.travis.yml, .travis/tests.sh
Wildfly 19.0.0.Beta1 has been released. We should verify that Krazo runs fine against new versions as early as possible. Unfortunately there is no Docker image yet. So we cannot update the testsuite as well.
=> New job to run TCK against Wildfly 19.0.0.Beta1

core/pom.xml, core/src/test/java/org/eclipse/krazo/util/AnnotationUtilsTest.java
see: #115
The test dependencies within the core module are up-to-date now. Unfortunately,
Weld changed its behavior and wanted to load servlet related beans which
aren't necessary in this test. As a result, it didn't work anymore. As I don't see
any reason to use CDI for testing the annotation hierachy, I removed CDI and the test
passes again.
=> Update test dependencies in core module

testsuite/src/main/java/org/eclipse/krazo/test/annotations/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/csrf/base/CsrfBaseApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/csrf/methods/CsrfHiddenMethodApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/asciidoc/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/freemarker/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/handlebars/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/jade/JadeApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/jetbrick/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/jsr223/Jsr223Application.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/jtwig/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/mustache/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/stringtemplate/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/thymeleaf/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/ext/velocity/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/forms/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/mvc/MyApplication.java
To be able to run the tests on any server without the problem of a
not initialized Krazo feature, they are all set to autodiscover their
resources now. This way, they behave like the TCK tests and we can
test specific behavior (like we have in Jersey or RESTEasy) in own tests
=> Let tests autodiscover their resources

core/src/main/java/org/eclipse/krazo/bootstrap/DefaultConfigProvider.java, documentation/src/main/asciidoc/_quickstart.adoc
During the review of @erdlet's documentation PR I saw that's currently quite cumbersome to set up Krazo with CXF. We could make it easier by providing all default features.
=> Provide default features for implementation who need to register them manually

dependency-check-suppressions.xml, ext/handlebars/pom.xml
... we found in #74. There was nothing we could do back then, so we had to whitelist it.
Upstream fix: https://github.com/jknack/handlebars.java/issues/703
=> Update handlebars to fix a security issue

testsuite/src/main/java/org/eclipse/krazo/test/encoding/MyApplication.java
As CXF doesn't load our providers when overwriting `getClasses`, I added them manually to get this test run on Liberty
=> Load Providers for CXF manually

ext/handlebars/src/main/java/org/eclipse/krazo/ext/handlebars/HandlebarsViewEngine.java
As the title suggests, Handlebars {{#block}} partials were all being rendered on a single line, which can obviously cause issues, especially if you have inline JavaScript with comments.
Signed-off-by: Jonathan Putney <jonathan@putney.io>
=> Handlebars Block helper partials were being rendered on a single line

.travis.yml, .travis/start-glassfish.sh, README.md, testsuite/pom.xml, testsuite/src/test/resources/arquillian.xml
This PR adds a new profile to our testsuite setup to run the tests against Eclipse Glassfish. Travis is green, so it should be fine. :-)
I also added a description about how to run the testsuite against OpenLiberty. But for some weird reason this doesn't work for me locally, although I documented exactly what the Travis scripts is doing. But maybe I'm missing something obvious.
=> Added testsuite profile for Eclipse Glassfish

pom.xml
Looks like we are not allowed anymore to push artifacts to Sonatype OSSRH:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566865
The Eclipse Webmasters suggested trying the Eclipse Nexus instance. As we have to migrate to this one anyway in the long term, let's see if this fixes our current snapshot deployment issue.
Note: The Eclipse Nexus instance is defined in the EE4J parent, so we just have to remove our override.
=> Use Eclipse Nexus instead of Sonatype OSSRH for distribution

core/src/main/java/org/eclipse/krazo/KrazoConfig.java, core/src/main/java/org/eclipse/krazo/Properties.java, core/src/main/java/org/eclipse/krazo/cdi/KrazoCdiExtension.java, core/src/main/java/org/eclipse/krazo/forms/HiddenMethodFilter.java, testsuite/src/main/java/org/eclipse/krazo/test/csrf/methods/CsrfHiddenMethodApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/forms/MyApplication.java
At the moment, the HiddenMethodFilter is active all the time and checks every
request for possibly changed methods. I could imagine that this is not
wanted by every user, because they maybe want to use other mechanisms to
determine the HTTP method or just use the HTML Form standards. To ensure
that this feature doesn't cause trouble to anyone who isn't aware of the feature,
now a toggle is added to the KrazoProperties and the filter can be activated in the JAX-RS
application.
Signed-off-by: Tobias Erdle <tobias.erdle@innoq.com>
=> Activate hidden method filtering by toggle

.travis.yml, core/src/main/java/org/eclipse/krazo/binding/convert/impl/BigDecimalConverter.java, core/src/test/java/org/eclipse/krazo/binding/convert/impl/BigDecimalConverterTest.java, pom.xml
Not sure why thee BigDecimal conversion test failed after the switch.
Could be Double.NaN is treated differently in Java 8 and 11?
Actually not sure why it worked before either as it looks more correct now :)
Thiis commit is the interesting one: https://github.com/eclipse-ee4j/krazo/pull/215/commits/97dc817f7e114ec0dafe5d30565c879de6e847d5
(The other is just some plugin updates)
=> Fix tests after namespace switch

documentation/src/main/asciidoc/_quickstart.adoc
I noticed one of our web.xml examples in the documentation still uses the old "java.sun.com" namespace. We should replace that with the JCP-NS.
=> use jcp namespace in xml examples in quickstart

tck/pom.xml, tck/src/main/java/org/eclipse/krazo/tck/glassfish/GlassfishModuleArchiveProvider.java
A first version of a Maven profile to run the TCK against Glassfish with Krazo installed as a Glassfish module.
However, the TCK currently fails horribly. It looks like HK2 isn't able to do any CDI injections into our JAX-RS providers (like `ViewableWriter`). Also, I'm not seeing any logs which indicate that Krazo is bootstrapped correctly at all.
For a quick test, I added a `beans.xml` to `krazo-core` with discovery mode `all`. In this case it seems to work better, but Glassfish reports that our `ServletContainerInitializer` implementation cannot be loaded. So it looks like Glassfish finds our ServiceLoader file, but fails to load our implementation.
All of this is really weird. And IIRC it worked much better with Glassfish 5 back then.
Here a few tips on how to do similar experiments. …
=> New TCK runner profile for Glassfish with Krazo module

core/src/main/java/org/eclipse/krazo/bootstrap/Initializer.java, core/src/main/java/org/eclipse/krazo/jaxrs/JaxRsContextProducer.java
This PR contains two fixes which broke Krazo when installed as a Glassfish module. With these fixes Krazo now passes the TCK against Glassfish 6.1.0-M1 with Krazo installed in the `glassfish/modules` folder on JDK11. :tada: 
The two fixes are:
- Back then we created a mechanism for Krazo to detect if the "current application" contains MVC controllers and only bootstrap itself if controllers were found. However, this didn't work in CXF for some reason. Therefore, we added a fallback so that if discovery of controllers doesn't work, Krazo initializes nevertheless. When installed as a Glassfish module, this lead to the situation that Krazo was initialized even for internal Glassfish applications like the admin console which was causing followup errors. As CXF isn't or priority anymore, Krazo …
=> Allow to use Krazo as a Glassfish module

core/src/main/java/org/eclipse/krazo/jaxrs/PostMatchingRequestFilter.java, core/src/main/java/org/eclipse/krazo/jaxrs/PreMatchingRequestFilter.java
It seems, that the @Context annotation has problems with injecting our
JaxRsContextProducer also on RESTEasy. Unfortunately, the documentation
of @Context itself isn't very helpful, so I just reverted the change and
load the Producer manually again.
see: #250
=> Load JaxRsContextProducer via BeanManager again

core/pom.xml, ext/pom.xml, resteasy/pom.xml, testsuite/pom.xml
I'm working on preparing a release branch for the upcoming 2.0.1 release and found some issues with our dependencies.
* Most of the Jakarta EE API dependencies in the `core` module are `compile` instead of `provided`-scoped. I guess this was done by mistake during the namespace migration.
* The `testsuite` and the `ext` modules are still using the Jakarta EE 8 API (`javax.*` version). I guess this didn't cause any problems, because we pull in the individual spec JARs in the correct version as well via some transitive path.
* The `core` module has a `compile`-scoped dependency on the MVC API. We did this intentionally back then, but I guess it is time to change this and use `provided` scope as for all other APIs.
I ran the TCK for Glassfish and Wildfly locally and everything works fine. …
=> Fixed dependency scopes and versions

core/pom.xml, examples/csrf-property/pom.xml, examples/def-ext/pom.xml, examples/exceptions/pom.xml, examples/pom.xml, examples/redirectScope2/pom.xml, examples/redirectScope3/pom.xml, examples/uri-builder/pom.xml, examples/validation-i18n/pom.xml, ext/pom.xml, jersey/pom.xml, pom.xml, resteasy/pom.xml, tck/pom.xml, testsuite/pom.xml
As mentioned in #262, I created this PR to improve our dependency handling by moving some of the most important dependencies to a `<dependencyManagement>` section in the parent pom. I hope that this will simplify the process of updating dependencies in the future.
=> Added dependencyManagement in parent pom

tck/pom.xml
It looks like the changes introduced in #263 broke the TCK module, as there are now two `dependencyManagement` entries for the MVC API (one in the parent and one in the `tck` module itself). For some reason, ShrinkWrap isn't able to resolve the correct version in this case.
```
[INFO] Running jakarta.mvc.tck.tests.mvc.redirect.scope.RedirectScopeTest
org.jboss.shrinkwrap.resolver.api.ResolutionException: Unable to get version for dependency specified by jakarta.mvc:jakarta.mvc-api:compile, it was not provided in neither <dependencyManagement> nor <dependencies> sections.
at org.jboss.shrinkwrap.resolver.impl.maven.task.ResolveVersionFromMetadataTask.execute(ResolveVersionFromMetadataTask.java:124)
at org.jboss.shrinkwrap.resolver.impl.maven.PomEquippedResolveStageBaseImpl.resolveVersion(Po …
```
=> Removed duplicated dependencyManagement entry

README.md
Because we removed Travis as build tool, the tag isn't necessary anymore
=> Remove travis build tag

testsuite/pom.xml
This is needed for #274 to be able to use the latest version of `jinjava`. 
The reason for this is that the latest `jinjava` version depends on `guava` version `25.0-jre` and uses the method `com.google.common.collect.ImmutableMap.toImmutableMap` which is not present in the `guava` version imported by `shrinkwrap-resolver-bom` version `3.1.3`.
`shrinkwrap-resolver-bom` version `3.1.4` does not depend on `guava` anymore, so it should resolve the issue.
=> Update shrinkwrap-resolver-bom to latest version

testsuite/pom.xml
JDK 17 brought the strong encapsulated modules, which prevents our tests from accessing some JDK APIs during runtime via reflection.
By opening them in the failsafe plugin, we're able to run the tests again. On server side, this settings are done within the standalone.sh per default.
fixes: #278
=> Open java.security and java.io for tests

testsuite/src/main/java/org/eclipse/krazo/test/convert/available/AvailableConverterApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/convert/available/AvailableConverterController.java, testsuite/src/main/resources/convert/available/views/index.jsp, testsuite/src/test/java/org/eclipse/krazo/test/convert/AvailableConvertersIT.java
As it seems that the test was flaky because of the namespace change from
javax -> jakarta and a update of Arquillian and HTMLUnit didn't help, I
decided to replace the test with a similar one which runs outside the
container. This fixes the build errors on Glassfish and gives us the
same information.
fixes: #276
=> Replace test running inside container with remote variant

core/src/test/java/org/eclipse/krazo/binding/convert/impl/SupportsTest.java, core/src/test/java/org/eclipse/krazo/engine/ViewEngineBaseTest.java, core/src/test/java/org/eclipse/krazo/uri/ApplicationUrisTest.java, core/src/test/java/org/eclipse/krazo/uri/UriTemplateParserTest.java, core/src/test/java/org/eclipse/krazo/util/AnnotationUtilsTest.java, core/src/test/java/org/eclipse/krazo/util/BeanUtilsTest.java, core/src/test/java/org/eclipse/krazo/util/ControllerUtilsTest.java, core/src/test/java/org/eclipse/krazo/util/PathUtilsTest.java, core/src/test/java/org/eclipse/krazo/util/PropertyUtilsTest.java, testsuite/src/test/java/org/eclipse/krazo/test/mapper/ExceptionMapperIT.java
See warn: <T>assertThat(T,org.hamcrest.Matcher<? super T>) in org.junit.Assert has been deprecated
=> Fixed Maven warnings for deprecated org.junit.Assert.assertThat(...)

resteasy/src/main/java/org/eclipse/krazo/resteasy/core/LibertyHttpCommunicationUnwrapper.java, resteasy/src/main/resources/META-INF/services/org.eclipse.krazo.core.HttpCommunicationUnwrapper
This change should fix the trouble observed in https://github.com/eclipse-ee4j/krazo/issues/282 , allowing Krazo to work again on Liberty JEE 9 betas.
The test suites for WildFly and GlassFish should still pass without issue, but there's one test failure in Liberty. I believe it's unrelated to this change, though, and I'll create another issue to identify the trouble there.
=> eclipse-ee4j/krazo#282: Added HttpCommunicationWrapper for Liberty JEE9

ext/pom.xml, ext/thymeleaf/pom.xml, ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/CDIWebContext.java, ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/DefaultJakartaServletWebApplicationWrapperProducer.java, ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/DefaultTemplateEngineProducer.java, ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/JakartaServletWebApplicationWrapper.java, ext/thymeleaf/src/main/java/org/eclipse/krazo/ext/thymeleaf/ThymeleafViewEngine.java, testsuite/src/test/java/org/eclipse/krazo/test/ext/ThymeleafIT.java
This reenables the Thymeleaf extension by using its 3.1.0.M1 milestone release (which uses the jakarta namespace).
To adapt to changes in Thymeleaf, CDIWebContext had to be changed to use the jakarta namespace and the new IWebExchange. Since `JakartaServletWebApplication` has been established to wrap ServletContext in Thymeleaf, there needed to be a producer to inject it into both `DefaultTemplateEngineProducer` and `ThymeleafViewEngine`. But because `JakartaServletWebApplication` is a final class, a wrapper for it had to be written in order to use CDI.
Fixes #233
=> [#233] Reactivating the Thymeleaf extension

core/src/main/java/org/eclipse/krazo/util/AnnotationUtils.java
The TCK started to fail against Glassfish 7.0.0-SNAPSHOT (see #299 for details). 
One of the reasons seems to be that the latest Weld releases use a new naming pattern for CDI proxies, which causes our proxy detection mechanism to break. 
The old mechanism was based on the assumption that the FQCN of the proxy class this the name of the original class followed by `$$` and some fixes string. This isn't the case anymore as Weld seems to add an additional package prefix.
However, actually it should be sufficient to check if the class is synthetic and has a superclass.
Actually, we could even skip the class name pattern check and just check for the synthetic flag, but I decided to keep the old check for backwards compatibility.
=> Improved proxy class detection mechanism (fixes #299)

core/pom.xml, jersey/pom.xml, resteasy/pom.xml
The same as https://github.com/eclipse-ee4j/mvc-api/pull/79, but for Krazo.
=> Remove upper version bounds from OSGi Import-Package

core/src/main/java/org/eclipse/krazo/KrazoConfig.java, core/src/main/java/org/eclipse/krazo/Properties.java, core/src/main/java/org/eclipse/krazo/bootstrap/DefaultConfigProvider.java, core/src/main/java/org/eclipse/krazo/cdi/KrazoCdiExtension.java, core/src/main/java/org/eclipse/krazo/forms/FormMethodOverwriteFilter.java, core/src/main/java/org/eclipse/krazo/security/CsrfValidateFilter.java, tck/pom.xml, testsuite/src/main/java/org/eclipse/krazo/test/csrf/methods/CsrfHiddenMethodApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/forms/MyApplication.java
This PR implements the newly specified feature 'form method overwrite' and fixes the TCK runner for WildFly on higher JDKs.
As Glassfish ships with a other version of Krazo, the TCK failed there. On WildFly 26 everything went fine. I'd recommend to release a Krazo milestone afterwards which maybe can be put into the Glassfish Beta, so we can test against it.
=> Implement specified form method overwrite

documentation/src/main/asciidoc/_advanced.adoc
This change adds the changes from Jakarta MVC 2.1 related to the form method overwrite into the documentation.
Also, it adds the necessary migration steps to replace the legacy config of Krazo's HiddenMethodFilter.
fixes: #300
=> Update form method overwrite topic

pom.xml
To save build time the dependency update check and OWASP security
check should run only when the new flags dependencyCheckSkip for the
OWASP or versionUpdateSkip for the versions maven plugin are set to
false.
fixes: #311 #312
=> Run OWASP and depedency version check explicitely

core/src/main/java/org/eclipse/krazo/core/ViewResponseFilter.java, core/src/main/java/org/eclipse/krazo/core/ViewableWriter.java, core/src/main/java/org/eclipse/krazo/jaxrs/JaxRsContextProducer.java, core/src/main/java/org/eclipse/krazo/jaxrs/PostMatchingRequestFilter.java, core/src/main/java/org/eclipse/krazo/jaxrs/PreMatchingRequestFilter.java, core/src/main/java/org/eclipse/krazo/security/CsrfTokenManager.java
It seems that creating a HttpServletRequestBean by Krazo in the JaxRsContextProducer
leads to errors in the CDI TCK because there is already a default for HttpServletRequests
implemented. Removing this producer fixes two CDI tests.
see: #317
=> Remove producer for HttpServletRequest

pom.xml
The updated version contains a fix for the currently failing TCK test.
=> Upgrade TCK to 2.0.1.RC2

tck/pom.xml, tck/src/test/resources/arquillian.xml
As there are weird download issues when running the remote TCK job for
WildFly, this new profile enables us to use a managed WildFly instance.
=> Add managed profile for WildFly TCK

pom.xml, tck/pom.xml, tck/src/test/resources/liberty/server.xml, testsuite/pom.xml, testsuite/src/test/resources/arquillian.xml, testsuite/src/test/resources/liberty/server.xml
This enables us to launch the Open Liberty testsuite and TCK again.
Anyway, the testsuite fails because we don't implement some IBM specific wrapper and the TCK because
I'm not able to get the names of currently supported Jakarta EE 10 features, so the tests fail because of invalid `web.xml` versions. 
As those are managed environments, it won't be necessary to download the servers manually in Jenkins. I'll do the relevant changes there.
=> Update liberty arquillian settings

Jenkinsfile
Made a little mistake which only occurs in the testsuite when a core artifact needs a new build. This won't happen with just `mvn compile`, so I made the second step to test and install the artifacts.
=> Install compile dependencies in local maven repo

README.md, documentation/src/main/asciidoc/_configuration.adoc, documentation/src/main/asciidoc/_extensions.adoc, documentation/src/main/asciidoc/_intro.adoc, documentation/src/main/asciidoc/_quickstart.adoc, documentation/src/main/asciidoc/_view-engines.adoc
- Remove version of Jakarta MVC
- Add hint which Jakarta EE version is assumed as default
Improve quickstart documentation
- Remove duplicated information
- Fix parsing issues in XML listings
- Remove most of CXF specific information
- Remove information about 'context.xml' as there are no problems
without it (at least T. Erdle couldn't encounter them)
- Remove detail information about Thorntail
Update copyright date
Replace JAX-RS with Jakarta REST inside quickstart
Extend missing documentation
- Describe common configuration properties
- Describe out of the box view engines
- Describe the Krazo SPIs
Describe how view engine can be implemented
Replace GitHub CI badge with Jenkins badge
fixes: #330
=> Improve documentation and README

archetype/pom.xml, archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetype/src/main/resources/archetype-resources/pom.xml, archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/beans.xml, archetype/src/main/resources/archetype-resources/src/test/java/AppTest.java, documentation/src/main/asciidoc/_quickstart.adoc
This PR updates the archetype according to #336. As stated in the first commit, I changed the name so we have _one_ archetype artifact whose Jakarta EE release is equal to the API version's. Also it updates to JUnit 5, as Arquillian seems to run well with it in the meanwhile.
=> 336 update archetype for ee10

core/src/main/java/org/eclipse/krazo/util/AnnotationUtils.java, core/src/test/java/org/eclipse/krazo/util/AnnotationUtilsTest.java, resteasy/src/main/java/org/eclipse/krazo/resteasy/validation/KrazoGeneralValidator.java
While fixing #334 (PR #335) we introduced a small bug during the check if a method needs to be processed by the general validator or not. Because of this bug, the implementation checked only if a method is annotated with `@Controller`, but not if this is the case for the whole class. The result was Krazo not handling invalid input correctly.
This fix adds the ability to check if the method OR the declaring class is annotated with `@Controller`, so we ensure we really have something that needs to be handled by MVC.
This fix needs to be backported to Krazo 3.0.x.
fixes: #342
=> Fix annotation check for controller methods in RESTEasy

pom.xml
Update 2.0.x dependencies to avoid CVE warnings:
* Jersey 3.0.8
=> Update 2.0.x dependencies to avoid CVE warnings.

core/src/main/java/org/eclipse/krazo/util/AnnotationUtils.java, core/src/test/java/org/eclipse/krazo/util/AnnotationUtilsTest.java, jersey/src/main/java/org/eclipse/krazo/jersey/validation/KrazoValidationInterceptor.java, resteasy/src/main/java/org/eclipse/krazo/resteasy/validation/KrazoGeneralValidator.java, testsuite/pom.xml, testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/MixedResource.java, testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/MyApplication.java, testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/Todo.java, testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/TodoForm.java, testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/TodoHolder.java, testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/package-info.java, testsuite/src/main/resources/mixedsetup/views/index.jsp, testsuite/src/test/java/org/eclipse/krazo/test/mixedsetup/MixedSetupValidationIT.java
This commit backports the validation issue when using mixed MVC and non-MVC methods. Because the original test is using JDK 11 API, an external HTTP client was added in test scope.
@ivargrimstad  / @chkal please do me a favor and run the tests locally. I think I got weird failures because of my JVM / Glassfish settings.
=> Ignore non-MVC requests when validating input

resteasy/src/main/java/org/eclipse/krazo/resteasy/core/WeldHttpCommunicationUnwrapper.java, resteasy/src/main/resources/META-INF/services/org.eclipse.krazo.core.HttpCommunicationUnwrapper
Follow-up on #364. This change gets Krazo working on OpenLiberty 22.0.0.13-beta with Jakarta EE 10.
I have added the HttpCommunicationWrapper next to the existing one, introduced in #288. I don't know if they should live together, or if this one should replace the previous one. When living together, I'm not sure about the priority of one vs. the other.
=> Added HttpCommunicationWrapper for Liberty Jakarta EE 10
