core/src/test/java/org/eclipse/krazo/security/DefaultFormEntityProviderTest.java

[#46] Replace random byte array with hard coded garbage

---

.travis/docker-wildfly.sh
.travis/tests.sh
cxf/pom.xml

Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>
small update to wildfly, wlp and cxf

small updates

---

core/src/main/java/org/eclipse/krazo/core/ViewResponseFilter.java

For some reason Jersey 2.28 executes our view filter twice. This results in duplicated MvcEvents being fired, which results in TCK failures. This workaround fixes this issue.

Ensure ViewResponseFilter is executed only once

---

ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleViewEngine.java

Fixes one off the test failures from #76

Make the pebble view engine proxyable to fix a test failure on TomEE

---

testsuite/pom.xml
testsuite/src/test/java/org/eclipse/krazo/test/annotation/IgnoreOnWildfly.java
testsuite/src/test/java/org/eclipse/krazo/test/ext/AsciiDocIT.java
testsuite/src/test/java/org/eclipse/krazo/test/ext/Jsr223IT.java

Disable AsciiDocIT on wildfly.

---

pom.xml

Upgrade commons-beanutils to close vulnerability.

---

cxf/pom.xml
resteasy/pom.xml

this pr make update to CXF and RestEasy . 
Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>

update dependencies to CXF and RestEasy

---

.travis/tests.sh
pom.xml
tck/pom.xml

Update to RC1 versions of the spec and the TCK.

Updated MVC + TCK versions to 1.0.0-RC1

---

ext/pebble/pom.xml

Increase pebble version to 3.1.1

---

testsuite/pom.xml

Update TomEE arquillian adapter to 8.0.0 and fix scope

---

documentation/src/main/asciidoc/_advanced.adoc
documentation/src/main/asciidoc/_configuration.adoc
documentation/src/main/asciidoc/_extensions.adoc
documentation/src/main/asciidoc/_quickstart.adoc
documentation/src/main/asciidoc/_view-engines.adoc

Adds the basic structure for the top-level chapters of the documentation.

Basic chapter structure for documentation

---

examples/application-path/src/test/java/org/eclipse/krazo/test/applicationpath/ApplicationPathIT.java
examples/book-cdi/src/test/java/org/eclipse/krazo/test/bookcdi/BookCdiIT.java
examples/book-models/src/test/java/org/eclipse/krazo/test/bookmodels/BookModelsIT.java
examples/conversation/src/test/java/org/eclipse/krazo/test/conversation/ConversationIT.java
examples/csrf-property/src/test/java/org/eclipse/krazo/test/csrfproperty/CsrfIT.java
examples/def-ext/src/test/java/org/eclipse/krazo/test/mvc/DefaultExtensionIT.java
examples/events/src/test/java/org/eclipse/krazo/test/events/EventsIT.java
examples/exceptions/src/test/java/org/eclipse/krazo/test/exceptions/ExceptionsIT.java
examples/facelets/src/test/java/org/eclipse/krazo/test/facelets/FaceletsIT.java
examples/locale/src/test/java/org/eclipse/krazo/test/locale/LocaleIT.java
examples/pom.xml
examples/produces/src/test/java/org/eclipse/krazo/test/produces/ProducesIT.java
examples/redirect/src/test/java/org/eclipse/krazo/test/redirect/RedirectIT.java
examples/redirectScope/src/test/java/org/eclipse/krazo/test/redirectscope/RedirectScopeIT.java
examples/redirectScope2/src/test/java/org/eclipse/krazo/test/redirectscope2/RedirectScopeIT.java
examples/requestDispatcher/src/test/java/org/eclipse/krazo/test/requestdispatcher/RequestDispatcherIT.java
examples/returns/src/test/java/org/eclipse/krazo/test/returns/ReturnsIT.java
examples/uri-builder/src/test/java/org/eclipse/krazo/test/uribuilder/UriBuilderIT.java
examples/validation-i18n/src/test/java/org/eclipse/krazo/test/validation/I18NValidationIT.java
examples/validation/src/test/java/org/eclipse/krazo/test/validation/ValidationIT.java
examples/view-annotation/src/test/java/org/eclipse/krazo/test/view/ViewAnnotationIT.java

Update htmlunit to current version for examples

---

ext/stringtemplate/pom.xml

Update ST4 to latest version

---

core/pom.xml

Unfortunately I missed this dependency while updating the core. So here is the last PR for this long list of updates :)
see: #115

Update forgotten javax-el implementation

---

.travis/docker-tomee.sh
testsuite/pom.xml

Update TomEE to latest version for testsuite execution

---

archetype/pom.xml
archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
archetype/src/main/resources/archetype-resources/pom.xml
archetype/src/main/resources/archetype-resources/src/main/java/App.java
archetype/src/main/resources/archetype-resources/src/main/java/controller/AppController.java
archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/beans.xml
archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/views/hello.jsp
archetype/src/main/resources/archetype-resources/src/test/java/AppTest.java
documentation/src/main/asciidoc/_quickstart.adoc
pom.xml

As mentioned in #162, I created an archetype for Jakarta EE projects with the MVC API and Krazo a few months ago. But I think, that this archetype is better placed in the Krazo repo, as it is released in sync with out newest versions then.

Add archetype

---

documentation/src/main/asciidoc/_quickstart.adoc

Document manual Krazo config for CXF

---

archetype/pom.xml
archetype/src/main/resources/archetype-resources/src/main/java/App.java
archetype/src/main/resources/archetype-resources/src/main/java/controller/AppController.java

Fix class templates and improve artifact name

---

documentation/src/main/asciidoc/_quickstart.adoc

Use correct archetype name in documentation

---

archetype/src/main/resources/archetype-resources/src/test/java/AppTest.java

Fix package for generated test

---

documentation/src/main/asciidoc/_quickstart.adoc

Migrate missing quickstart documentation

---

documentation/src/main/asciidoc/_configuration.adoc

Add documentation about MVC and Krazo configuration

---

CONTRIBUTING.md

Add development process elements to contributing file

---

core/src/main/java/org/eclipse/krazo/core/ViewableWriter.java
core/src/main/java/org/eclipse/krazo/engine/ServletViewEngine.java
core/src/test/java/org/eclipse/krazo/core/ViewableWriterTest.java
examples/produces/src/main/webapp/WEB-INF/views/hello.jsp
testsuite/src/main/java/org/eclipse/krazo/test/encoding/EncodingController.java
testsuite/src/main/java/org/eclipse/krazo/test/encoding/MyApplication.java
testsuite/src/main/resources/encoding/views/iso-8859-15.jsp
testsuite/src/main/resources/encoding/views/iso-8859-15.xhtml
testsuite/src/main/resources/encoding/web.xml
testsuite/src/test/java/org/eclipse/krazo/test/EncodingIT.java
testsuite/src/test/java/org/eclipse/krazo/test/util/WebArchiveBuilder.java

Fixes https://github.com/eclipse-ee4j/krazo/issues/22

Don't ignore the contentType of the JSP page directive

---

ext/pebble/README.md
ext/pebble/pom.xml
ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleEngineProducer.java
ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleViewEngine.java

Pebble dependency update, better README.md and Javadoc and better instance creation(for JDKs > 8 removed usage of deprecated Class.forName(...).newInstance() method).

Pebble extension maintenance PR

---

.travis/docker-tomee.sh
testsuite/pom.xml

Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>

update version of tomee 8.0.1 to 8.0.2

---

documentation/src/main/asciidoc/_quickstart.adoc

Update Thorntail information

---

core/src/main/java/org/eclipse/krazo/engine/ViewEngineBase.java
ext/handlebars/src/main/java/org/eclipse/krazo/ext/handlebars/DefaultHandlebarsProducer.java
ext/handlebars/src/main/java/org/eclipse/krazo/ext/handlebars/HandlebarsViewEngine.java
testsuite/src/main/resources/handlebars/views/head.hbs
testsuite/src/main/resources/handlebars/views/person.hbs
testsuite/src/test/java/org/eclipse/krazo/test/ext/HandlebarsIT.java

Handlebars default TemplateLoader was not able to find partials (Fixes #186)

---

core/src/main/java/org/eclipse/krazo/KrazoConfig.java

Signed-off-by: Daniel Dias <daniel.dias.analistati@gmail.com>

Replace String to Constants for CSRF 

---

README.md

Add documentation about running tests on WildFly

---

README.md

To avoid merge conflicts, this PR depends on #190. Please just review the TomEE part here :)

188 add tomee testsuite documentation

---

.travis.yml
.travis/tests.sh
archetype/src/main/resources/archetype-resources/pom.xml
core/pom.xml
cxf/pom.xml
examples/pom.xml
ext/pom.xml
jersey/pom.xml
pom.xml
resteasy/pom.xml
tck/pom.xml
testsuite/pom.xml

Merging this will require Krazo to be built using `-Pstaging`. 
Not sure if we should set that as a default profile, or maybe it is enough to add instructions to the README.
Travis job will most likely fail as well, any thoughts?

Upgrade to Jakarta MVC 1.1-SNAPSHOT

---

pom.xml

Signed-off-by: Thiago Henrique Hüpner <thihup@gmail.com>

Update JaCoCo to enable build with JDK11+

---

.travis.yml
.travis/tests.sh
pom.xml

Update to api 1.1-RC1

---

.travis.yml
.travis/tests.sh

Use default maven profile

---

.travis.yml
.travis/tests.sh
dependency-check-suppressions.xml
pom.xml

Update refs to MVC 1.1.0

---

documentation/src/main/asciidoc/_quickstart.adoc

As Thorntail won't be actively developed in the future, we should warn
users of the fraction that there won't be active development either.
Signed-off-by: Tobias Erdle <tobias.erdle@innoq.com>

Add hint for Thorntail EOL

---

README.md

Update readme for website

---

documentation/src/main/asciidoc/_advanced.adoc

Signed-off-by: Tobias Erdle <tobias.erdle@innoq.com>

Document usage of HiddenMethodFilter

---

core/src/main/java/org/eclipse/krazo/binding/BindingErrorImpl.java
core/src/main/java/org/eclipse/krazo/binding/convert/ConverterResult.java
core/src/main/java/org/eclipse/krazo/cdi/KrazoCdiExtension.java
core/src/main/java/org/eclipse/krazo/cdi/RedirectScopeManager.java
core/src/main/java/org/eclipse/krazo/cdi/types/AnnotatedTypeProcessor.java
core/src/main/java/org/eclipse/krazo/core/ViewResponseFilter.java
core/src/main/java/org/eclipse/krazo/core/ViewableWriter.java
core/src/main/java/org/eclipse/krazo/engine/ViewEngineFinder.java
core/src/main/java/org/eclipse/krazo/jaxrs/PostMatchingRequestFilter.java
core/src/main/java/org/eclipse/krazo/jaxrs/PreMatchingRequestFilter.java
core/src/main/java/org/eclipse/krazo/locale/LocaleResolverChain.java
core/src/main/java/org/eclipse/krazo/security/CsrfProtectFilter.java
core/src/main/java/org/eclipse/krazo/security/CsrfValidateFilter.java
core/src/main/java/org/eclipse/krazo/security/EncodersImpl.java
core/src/main/java/org/eclipse/krazo/servlet/KrazoContainerInitializer.java
core/src/main/java/org/eclipse/krazo/uri/ApplicationUris.java
core/src/main/java/org/eclipse/krazo/uri/UriTemplate.java
core/src/main/java/org/eclipse/krazo/util/BeanUtils.java
core/src/main/java/org/eclipse/krazo/util/CdiUtils.java
core/src/main/java/org/eclipse/krazo/util/ServiceLoaders.java

This commit performs some basic code cleanup like removing unused
imports, setting final where possible and improves the usage of the Java
8 Stream API.
Signed-off-by: Tobias Erdle <tobias.erdle@innoq.com>

Do some code cleanup

---

documentation/src/main/asciidoc/_quickstart.adoc

Fix documentation about using metadata-complete

---

.travis.yml
.travis/install-liberty.sh
.travis/wlp-server-template.xml

Some first steps for running the TCK against OpenLiberty. But something is still not working. However, I configured Travis to allow failures for now. So maybe it is ok to merge this.

Some first steps for running the TCK against OpenLiberty

---

.travis.yml
.travis/start-wildfly.sh
.travis/tests.sh

Configure Travis to run the TCK against Wildfly 22 Preview

Run TCK against Wildfly 22

---

.travis.yml
.travis/docker-wildfly.sh
.travis/tests.sh
testsuite/src/test/java/org/eclipse/krazo/test/ext/HandlebarsIT.java
testsuite/src/test/java/org/eclipse/krazo/test/ext/JetbrickIT.java
testsuite/src/test/java/org/eclipse/krazo/test/ext/JtwigIT.java
testsuite/src/test/java/org/eclipse/krazo/test/ext/PebbleIT.java
testsuite/src/test/java/org/eclipse/krazo/test/ext/ThymeleafIT.java
testsuite/src/test/java/org/eclipse/krazo/test/util/WebArchiveBuilder.java

This PR reactivates our testsuite and runs it against Wildfly 22 Preview. Looks like this works fine! :-)

Run testsuite against Wildfly 22

---

tck/pom.xml
tck/src/main/java/org/eclipse/krazo/tck/liberty/LibertyDevArchiveProvider.java
tck/src/test/resources/arquillian.xml

Update OpenLiberty config

---

documentation/src/main/asciidoc/_quickstart.adoc

Update quickstart documentation regarding archetype

---

archetype/src/main/resources/archetype-resources/src/main/java/App.java

Set CSRF to implicit on generated application

---

ext/pebble/pom.xml
ext/pebble/src/main/java/org/eclipse/krazo/ext/pebble/PebbleEngineProducer.java
ext/pebble/src/test/java/org/eclipse/krazo/ext/pebble/PebbleEngineProducerTest.java
ext/pom.xml
testsuite/src/test/java/org/eclipse/krazo/test/ext/PebbleIT.java

Please don't merge before the version update. Needs to be done here manually.
closes: #234

Reactivate Pebble extension

---

core/src/main/resources/META-INF/web-fragment.xml

Added <distributable/> to web-fragment.xml (fixes #265)

---

pom.xml

Remove directory-maven-plugin to fix build on JDK 11

---

pom.xml

Update JaCoCo plugin to 0.8.7

---

ext/jinja2/pom.xml
ext/jinja2/src/main/java/org/eclipse/krazo/ext/jinja2/DefaultJinjavaProducer.java
ext/jinja2/src/main/java/org/eclipse/krazo/ext/jinja2/Jinja2ViewEngine.java
ext/jinja2/src/main/resources/META-INF/beans.xml
ext/pom.xml
testsuite/pom.xml
testsuite/src/main/java/org/eclipse/krazo/test/ext/jinja2/HelloController.java
testsuite/src/main/java/org/eclipse/krazo/test/ext/jinja2/MyApplication.java
testsuite/src/main/resources/jinja2/views/hello.j2
testsuite/src/test/java/org/eclipse/krazo/test/ext/Jinja2IT.java

Hello everyone!
So I played a bit around with Krazo and wanted to try and write my own ViewEngine.
Since there wasn't any Jinja2 ViewEngine yet, I wrote this one.
If you like it, you can merge it. If not, I'll probably put this into its own seperate repository for people to find.
Tell me what you think.

Jinja2 ViewEngine extension

---

core/pom.xml
examples/application-path/src/test/java/org/eclipse/krazo/test/applicationpath/ApplicationPathIT.java
examples/book-cdi/src/test/java/org/eclipse/krazo/test/bookcdi/BookCdiIT.java
examples/book-models/src/test/java/org/eclipse/krazo/test/bookmodels/BookModelsIT.java
examples/conversation/src/test/java/org/eclipse/krazo/test/conversation/ConversationIT.java
examples/csrf-property/src/test/java/org/eclipse/krazo/test/csrfproperty/CsrfIT.java
examples/def-ext/src/test/java/org/eclipse/krazo/test/mvc/DefaultExtensionIT.java
examples/events/src/test/java/org/eclipse/krazo/test/events/EventsIT.java
examples/exceptions/src/test/java/org/eclipse/krazo/test/exceptions/ExceptionsIT.java
examples/facelets/src/test/java/org/eclipse/krazo/test/facelets/FaceletsIT.java
examples/pom.xml
examples/produces/src/test/java/org/eclipse/krazo/test/produces/ProducesIT.java
examples/redirect/src/test/java/org/eclipse/krazo/test/redirect/RedirectIT.java
examples/returns/src/test/java/org/eclipse/krazo/test/returns/ReturnsIT.java
examples/uri-builder/src/test/java/org/eclipse/krazo/test/uribuilder/UriBuilderIT.java
examples/validation/src/test/java/org/eclipse/krazo/test/validation/ValidationIT.java
examples/view-annotation/src/test/java/org/eclipse/krazo/test/view/ViewAnnotationIT.java
ext/asciidoc/pom.xml
ext/freemarker/pom.xml
ext/mustache/pom.xml
ext/pebble/pom.xml
ext/stringtemplate/pom.xml
ext/velocity/pom.xml
jersey/pom.xml
pom.xml
resteasy/pom.xml
tck/pom.xml
testsuite/pom.xml
testsuite/src/test/java/org/eclipse/krazo/test/EncodingIT.java
testsuite/src/test/java/org/eclipse/krazo/test/annotations/AnnotationsIT.java

Added `versions-maven-plugin` for automatic dependencies versions checking during the build. Use Maven phase `verify` for this purpose.

Check all dependencies for updates and update them

---

documentation/src/main/asciidoc/_intro.adoc

The intro referred to the old specification names which are replaced by the Jakarta pendants.

Relate to Jakarta specifications

---

README.md
archetype/pom.xml
core/pom.xml
core/src/main/java/org/eclipse/krazo/forms/FormMethodOverwriteFilter.java
documentation/pom.xml
examples/pom.xml
ext/asciidoc/pom.xml
ext/freemarker/pom.xml
ext/jade/pom.xml
ext/jinja2/pom.xml
ext/mustache/pom.xml
ext/pebble/pom.xml
ext/pom.xml
ext/stringtemplate/pom.xml
ext/thymeleaf/pom.xml
ext/velocity/pom.xml
jersey/pom.xml
pom.xml
resteasy/pom.xml
tck/pom.xml
testsuite/pom.xml
testsuite/src/test/java/org/eclipse/krazo/test/util/WebArchiveBuilder.java
testsuite/src/test/resources/beans.xml

@ivargrimstad I'll check if there are CQs required. If yes, I'll add the tag and link to the CQs.

Jakartaee 10 upgrade

---

core/src/main/java/org/eclipse/krazo/binding/convert/MvcConverterProvider.java
core/src/main/java/org/eclipse/krazo/jaxrs/PostMatchingRequestFilter.java
core/src/main/java/org/eclipse/krazo/jaxrs/PreMatchingRequestFilter.java
core/src/main/java/org/eclipse/krazo/locale/DefaultLocaleResolver.java
examples/locale/src/main/java/org/eclipse/krazo/test/locale/QueryLocaleResolver.java
examples/validation-i18n/src/main/java/org/eclipse/krazo/test/validation/QueryLocaleResolver.java
pom.xml
resteasy/pom.xml
resteasy/src/main/java/org/eclipse/krazo/resteasy/core/LibertyHttpCommunicationUnwrapper.java
resteasy/src/main/java/org/eclipse/krazo/resteasy/security/RestEasyFormEntityProvider.java
testsuite/src/main/java/org/eclipse/krazo/test/convert/annotations/AnnotationDrivenConverter.java
testsuite/src/main/java/org/eclipse/krazo/test/convert/type/AnswerToAllDoubleConverter.java

Replace hard coded priorities with Interceptor.Priority

---

jersey/src/main/java/org/eclipse/krazo/jersey/validation/KrazoValidationInterceptor.java
resteasy/src/main/java/org/eclipse/krazo/resteasy/validation/KrazoGeneralValidator.java
testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/MixedResource.java
testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/MyApplication.java
testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/Todo.java
testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/TodoForm.java
testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/TodoHolder.java
testsuite/src/main/java/org/eclipse/krazo/test/mixedsetup/package-info.java
testsuite/src/main/resources/mixedsetup/views/index.jsp
testsuite/src/test/java/org/eclipse/krazo/test/mixedsetup/MixedSetupValidationIT.java

Ignore non-MVC requests when validating input

---

pom.xml

PR for the issue https://github.com/eclipse-ee4j/krazo/issues/339

Updated all dependencies to final versions

---

pom.xml
tck/pom.xml
testsuite/pom.xml

Replace outdated Arquillian client with modern one

---

tck/pom.xml

Use correct dependency for glassfish-module-tck

---

testsuite/pom.xml

Update WildFly to latest release version

---

testsuite/src/main/java/org/eclipse/krazo/test/redirectboundary/RedirectApplication.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundary/RedirectBean.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundary/RedirectBoundaryAController.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundary/RedirectBoundaryBController.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundaryonroot/RedirectApplication.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundaryonroot/RedirectBean.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundaryonroot/RedirectBoundaryAController.java
testsuite/src/main/java/org/eclipse/krazo/test/redirectboundaryonroot/RedirectBoundaryBController.java
testsuite/src/main/resources/redirectboundary/views/a.jsp
testsuite/src/main/resources/redirectboundary/views/b.jsp
testsuite/src/main/resources/redirectboundaryonroot/views/a.jsp
testsuite/src/main/resources/redirectboundaryonroot/views/b.jsp
testsuite/src/test/java/org/eclipse/krazo/test/RedirectScopeBoundaryIT.java
testsuite/src/test/java/org/eclipse/krazo/test/RedirectScopeBoundaryOnRootIT.java

It seems that the problem described in #354 is some client specific issue. Both tests could not reproduce the error on framework level, so we might close this issue for now.
see: #354

Add tests for cookie behavior verification
